# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Azavea Branding Guide
email: info@azavea.com
description: > # this means to ignore newlines until "baseurl:"
  This is the branding guide for Azavea: a certified B Corporation, who builds advanced geospatial applications for civic and social impact while advancing the state-of-the-art through research.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: azavea
github_username: azavea
highlighter: rouge

# Build settings
markdown: kramdown
exclude:
  - Dockerfile
  - docker-compose.yml
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock
