#!/bin/bash

set -e

if [[ -n "${BRANDING_GUIDE_DEBUG}" ]]; then
    set -x
fi

DIR="$(dirname "$0")"

function usage() {
    echo -n \
"Usage: $(basename "$0")
Start and stop Jekyll server.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
      docker-compose up
    fi
fi