#!/bin/bash

set -e

if [[ -n "${BRANDING_GUIDE_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")
Build the Jekyll container image.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        docker-compose build

        docker-compose run --rm jekyll build
    fi
fi